### ISSUE TITLE
相關連結

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/i3thuan5#11]
http://tayal.pqwasan.org.tw/kmal/desktop/index.php

**Comment by sih4sing5hong5** [comment]
* 族語密碼APC活動辦法
  * http://apcevent2.fishweb.com.tw/e1/htm
* 烏衣行
  * http://wesingkasu.blogspot.tw/

**Comment by sih4sing5hong5** [comment]
http://prj.digimagic.com.tw/ntcmin700/

**Comment by a8568730** [comment]
已經完成
